### ISSUE TITLE
Incorrect crest conformer search energy when using mtd and optimization method

### ISSUE THREAD

**Issue by jevandezande** [crest-lab/crest#348]
Following the [custom conformational search example](https://crest-lab.github.io/crest-docs/page/documentation/inputfiles_examples.html#conformational-sampling-custom), the dynamics method affects the final energy after optimization.

**To Reproduce**
`geom.xyz`
```
5
Methane
C     0.0000000000    0.0000000000    0.0000000000
H     0.6250000000    0.6250000000    0.6250000000
H    -0.6250000000   -0.6250000000    0.6250000000
H    -0.6250000000    0.6250000000   -0.6250000000
H     0.6250000000   -0.6250000000   -0.6250000000
```
`input.toml`
```toml
input="geom.xyz"
runtype="imtd-gc"
multilevelopt = false

[calculation]
[[calculation.level]]
# MTD
method="gfnff"
weight=1.0

[[calculation.level]]
# Opt
method="gfn2"

[dynamics]
active=[1]
```
| MTD Method | Energy |
|----------------|----------|
| GFN-FF | -4.80606 |
| GFN0   | -8.53465 |
| GFN1   | -8.44947 |
| GFN2   | -8.35044 |
