### ISSUE TITLE
[BUG] `[dynamics] length_ps` ignored if set as integer

### ISSUE THREAD

**Issue by coltonbh** [crest-lab/crest#359]
**Describe the bug**
If `length_ps` is set using an integer (e.g., `3`) it will be ignored and dynamics will run for 20ps. If you set `3.0` it is respected.

**To Reproduce**
```toml
#This is a CREST input file
input = 'h2o.xyz'
runtype = 'dynamics'
threads = 16

#calculation data
[calculation]
elog = "energies.log"

[[calculation.level]]
method = "gfnff"
alpb = 'ch2cl2'

#molecular dynamics data
[dynamics]
length_ps = 3
tstep = 0.5 # femtoseconds
temp = 298.15 # in kelvin
```

h2o.xyz:

```
3

O  0.00754405315117895 0.39774343120556577 0.00000000000000000
H  -0.76710313705750643 -0.18439316493074823 0.00000000000000000
H  0.75955908390632709 -0.21335026627481793 0.00000000000000000
```

Observe that dynamics runs for 20ps.

**Expected behavior**
Setting `length_ps=3` (or any other integer) would run dynamics for 3 ps.

Related to [#351](https://github.com/crest-lab/crest/issues/351) by @jevandezande
