### ISSUE TITLE
Error reading temp parameter from toml file.

### ISSUE THREAD

**Issue by gVallverdu** [crest-lab/crest#363]
Hello

The temperature read in the `[dynamics]` bloc is wrong. The read value is the one of the tag on the previous line, or the default value if the temp keyword is on the first line.

The inputs are taken from [this one](https://crest-lab.github.io/crest-docs/page/documentation/inputfiles_examples.html#molecular-dynamics-extendedmetadynamics)

The error can be fixed of a real value is used for temp, instead of an integer value. Actually temp must be real.

**Describe the bug**
The value of `temp`, read in the input file is not valid.

**To Reproduce**
Crest 3.0.2 (binaries version on linux system)

Here are several examples with both the input file and the output stream

```toml
# CREST 3 input file
runtype='dynamics'

[calculation]
elog="energies.log"

[[calculation.level]]
method="gfn1"

[dynamics]
tstep=1.5        #unit : fs
temp=100         #temperature in kelvin
length_ps=250.0  #unit : ps
```

```
> Molecular dynamics settings
 MD time /ps        :    250.00
 dt /fs             :      1.50
 temperature /K     :      1.50
 max steps          :    166667
```

Here the value of temp is the one of the previous line (the tstep value).

Another example:
```toml
# CREST 3 input file
runtype='dynamics'

[calculation]
elog="energies.log"

[[calculation.level]]
method="gfn1"

[dynamics]
length_ps=250.0  #unit : ps
temp=100         #temperature in kelvin
tstep=1.5        #unit : fs
```

```
> Molecular dynamics settings
 MD time /ps        :    250.00
 dt /fs             :      1.50
 temperature /K     :    250.00
 max steps          :    166667
```

Here the value of temp is again the one of the previous tag.

Now, if I put temp on the first line of the [dynamics] block it takes the default value (300K).

```toml
# CREST 3 input file
runtype='dynamics'

[calculation]
elog="energies.log"

[[calculation.level]]
method="gfn1"

[dynamics]
temp=100         #temperature in kelvin
length_ps=250.0  #unit : ps
tstep=1.5        #unit : fs
```

```
> Molecular dynamics settings
 MD time /ps        :    250.00
 dt /fs             :      1.50
 temperature /K     :    300.00
 max steps          :    166667
```

**Expected behavior**
Temperature should be the value of temp in the toml file.

Using a real value for temp it works

```toml
# CREST 3 input file
runtype='dynamics'

[calculation]
elog="energies.log"

[[calculation.level]]
method="gfn1"

[dynamics]
length_ps=250.0  #unit : ps
temp=100.0         #temperature in kelvin
tstep=1.5        #unit : fs
```

```
> Molecular dynamics settings
 MD time /ps        :    250.00
 dt /fs             :      1.50
 temperature /K     :    100.00
 max steps          :    166667
```
